version: "3"
services:
  Frontend:
    image: "saehoon0501/ncc-client"
    mem_limit: 128m
    hostname: client
  Backend:
    image: "saehoon0501/ncc-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - MONGO_URI=$MONGO_URI
      - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
      - AWS_SECRET_KEY=$AWS_SECRET_KEY
  nginx:
    image: "saehoon0501/ncc-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
